# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""init assumption check models

Revision ID: 17dd6ab24acb
Revises: a992c22b17fb
Create Date: 2020-07-13 13:36:46.024897

"""

# revision identifiers, used by Alembic.
revision = '17dd6ab24acb'
down_revision = '2eaac4256f03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ISP_Capacity_Definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('isp_case', sa.String(length=50), nullable=True),
    sa.Column('scenario', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'isp_case', 'scenario')
    )
    op.create_table('ISP_Capacity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('technology', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('isp_cap_def_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['isp_cap_def_id'], ['ISP_Capacity_Definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'technology', 'year', 'isp_cap_def_id')
    )
    # op.alter_column('annotation', 'layer_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False)
    # op.alter_column('dbs', 'allow_csv_upload',
    #            existing_type=mysql.TINYINT(display_width=1),
    #            nullable=True,
    #            existing_server_default=sa.text("'1'"))
    # op.drop_constraint('slices_ibfk_1', 'slices', type_='foreignkey')
    # op.drop_constraint('slices_ibfk_2', 'slices', type_='foreignkey')
    # op.drop_column('slices', 'druid_datasource_id')
    # op.drop_column('slices', 'table_id')
    # op.alter_column('tab_state', 'autorun',
    #            existing_type=mysql.TINYINT(display_width=1),
    #            nullable=True)
    # op.drop_index('ix_tab_state_id', table_name='tab_state')
    # op.drop_index('ix_table_schema_id', table_name='table_schema')
    # op.drop_index('table_name', table_name='tables')
    # op.create_unique_constraint(None, 'tables', ['database_id', 'table_name'])
    # op.drop_index('ix_tagged_object_object_id', table_name='tagged_object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_tagged_object_object_id', 'tagged_object', ['object_id'], unique=False)
    # op.drop_constraint(None, 'tables', type_='unique')
    # op.create_index('table_name', 'tables', ['table_name'], unique=True)
    # op.create_index('ix_table_schema_id', 'table_schema', ['id'], unique=True)
    # op.create_index('ix_tab_state_id', 'tab_state', ['id'], unique=True)
    # op.alter_column('tab_state', 'autorun',
    #            existing_type=mysql.TINYINT(display_width=1),
    #            nullable=False)
    # op.add_column('slices', sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('slices', sa.Column('druid_datasource_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.create_foreign_key('slices_ibfk_2', 'slices', 'tables', ['table_id'], ['id'])
    # op.create_foreign_key('slices_ibfk_1', 'slices', 'datasources', ['druid_datasource_id'], ['id'])
    # op.alter_column('dbs', 'allow_csv_upload',
    #            existing_type=mysql.TINYINT(display_width=1),
    #            nullable=False,
    #            existing_server_default=sa.text("'1'"))
    # op.alter_column('annotation', 'layer_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=True)
    op.drop_table('ISP_Capacity')
    op.drop_table('ISP_Capacity_Definition')
    # ### end Alembic commands ###
