# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""non null constrain on simulation models

Revision ID: 2993f834e84a
Revises: 1e3d8a7518e9
Create Date: 2020-05-20 10:42:44.860653

"""

# revision identifiers, used by Alembic.
revision = '2993f834e84a'
down_revision = '1e3d8a7518e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('assumption', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # op.alter_column('project', 'client_id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            nullable=False)
    # op.alter_column('simulation', 'assumption_id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            nullable=False)
    op.alter_column('simulation', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('simulation', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # op.alter_column('simulation', 'project_id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            nullable=False)
    op.alter_column('simulation', 'report_type',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('simulation', 'run_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('simulation', 'run_no',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('simulation', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulation', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('simulation', 'run_no',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('simulation', 'run_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('simulation', 'report_type',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # op.alter_column('simulation', 'project_id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            nullable=True)
    op.alter_column('simulation', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('simulation', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # op.alter_column('simulation', 'assumption_id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            nullable=True)
    # op.alter_column('project', 'client_id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            nullable=True)
    op.alter_column('assumption', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
