# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""start end date for simulation

Revision ID: 61f9ad15bb83
Revises: e1cc039e2f8f
Create Date: 2020-04-29 13:28:19.305760

"""

# revision identifiers, used by Alembic.
revision = '61f9ad15bb83'
down_revision = 'e1cc039e2f8f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('simulation', sa.Column('start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('simulation', 'start_date')
    op.drop_column('simulation', 'end_date')
    # ### end Alembic commands ###
