# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""simulation log model

Revision ID: 75d0834ccacb
Revises: cd2c27b8321a
Create Date: 2020-04-29 09:39:59.645300

"""

# revision identifiers, used by Alembic.
revision = '75d0834ccacb'
down_revision = 'cd2c27b8321a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=512), nullable=True),
    sa.Column('action_object', sa.String(length=512), nullable=True),
    sa.Column('action_object_type', sa.String(length=20), nullable=True),
    sa.Column('dttm', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('simulation_log')
    # ### end Alembic commands ###
