# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Extend status length for log and sim, add s3 path back for assump

Revision ID: b0c9835b069e
Revises: 3ea653b5d694
Create Date: 2020-06-05 10:55:59.807433

"""

# revision identifiers, used by Alembic.
revision = 'b0c9835b069e'
down_revision = '3ea653b5d694'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assumption', sa.Column('s3_path', sa.String(length=200), nullable=True))
    with op.batch_alter_table("simulation_log") as batch_op:
        batch_op.alter_column(
            "result",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=128),
            existing_nullable=True,
        )
    with op.batch_alter_table("simulation") as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=128),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("simulation") as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=10),
            existing_nullable=True,
        )
    with op.batch_alter_table("simulation_log") as batch_op:
        batch_op.alter_column(
            "result",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )
    op.drop_column('assumption', 's3_path')
    # ### end Alembic commands ###
