# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""simulation model change

Revision ID: cd2c27b8321a
Revises: a0355cb9c83a
Create Date: 2020-04-28 09:47:50.246847

"""

# revision identifiers, used by Alembic.
revision = 'cd2c27b8321a'
down_revision = 'a0355cb9c83a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assumption', 's3_path')

    op.add_column('simulation', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('simulation', sa.Column('run_id', sa.String(length=20), nullable=True))
    op.add_column('simulation', sa.Column('run_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('simulation', 'run_no')
    op.drop_column('simulation', 'run_id')
    op.drop_column('simulation', 'description')

    op.add_column('assumption', sa.Column('s3_path', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
