# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""adjust simulation and assumption relationship

Revision ID: e1cc039e2f8f
Revises: 75d0834ccacb
Create Date: 2020-04-29 10:48:45.136943

"""

# revision identifiers, used by Alembic.
revision = 'e1cc039e2f8f'
down_revision = '75d0834ccacb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('simulation_assumption')

    op.add_column('simulation', sa.Column('assumption_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'simulation', 'assumption', ['assumption_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation', type_='foreignkey')
    op.drop_column('simulation', 'assumption_id')
    op.create_table('simulation_assumption',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('simulation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('assumption_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumption.id'], name='simulation_assumption_ibfk_1'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], name='simulation_assumption_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
