# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""client and project model

Revision ID: efa5acce0db1
Revises: 03e58aeb73d6
Create Date: 2020-05-15 13:58:38.677703

"""

# revision identifiers, used by Alembic.
revision = 'efa5acce0db1'
down_revision = '03e58aeb73d6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('simulation', sa.Column('generation_model', sa.String(length=20), nullable=True))
    op.add_column('simulation', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('simulation', sa.Column('report_type', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'simulation', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation', type_='foreignkey')
    op.drop_column('simulation', 'report_type')
    op.drop_column('simulation', 'project_id')
    op.drop_column('simulation', 'generation_model')
    op.drop_table('project')
    op.drop_table('client')
    # ### end Alembic commands ###
