# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""add chart links to sim, log time in aest

Revision ID: fc472dad3d79
Revises: 17dd6ab24acb
Create Date: 2020-07-28 11:24:05.887922

"""

# revision identifiers, used by Alembic.
revision = 'fc472dad3d79'
down_revision = '17dd6ab24acb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_name', sa.String(length=128), nullable=True),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('chart_link', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('simulation', sa.Column('run_dttm', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation', 'run_dttm')
    op.drop_table('chart_simulation')
    # ### end Alembic commands ###
